title: Nathan Herrmann | Software Engineer II
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Nathan Herrmann"
job: "Software Engineer II"

phone_number: 801-368-7037
address: South Bend, Indiana
email: NathanJHerrmann@gmail.com
linkedin_username: nathor
github_username: nathor
instagram_username: instagram
twitter_username: twitter
facebook_username: facebook
youtube_username: youtube
blog_url:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag